version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
